[package]
name = "nonsense"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Sylvan Franklin"]
license = "MIT-0"
repository = "https://github.com/sylvanfranklin/nonsense"
categories = ["Fun"]
keywords = ["Fun"]
exclude = ["*.pdf", "*.jpg, *.gif"]
description = "Generate nonsensical math papers or sections of them."

[template]
path = "lib"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
